### ISSUE TITLE
Add registry from Cellosaurus

### ISSUE THREAD

**Issue by cthoyt** [bioregistry/bioregistry#98]
https://ftp.expasy.org/databases/cellosaurus/cellosaurus_xrefs.txt

**Comment by cmungall** [comment]
random sidebar

I think it represents a bit of a disappointing failure of us in OBO to communicate our PURL strategy that we have entries like:

Abbrev: CLO
Name  : Cell Line Ontology
Server: http://www.clo-ontology.org
Db_URL: https://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http://purl.obolibrary.org/obo/%s
Cat   : Ontologies

First, the PURL should be used directly, so that the OBO registry can redirect to wherever CLO regards as the canonical URL.

If done correctly, then bioregistry can provide all the alternate URLs correctly

This also reifies the CLO_nnnnn-as-iD confusion we see throughout identifiers.org etc

CLO:nnnnn is the CURIE
the prefix is http://purl.obolibrary.org/obo/CLO_

**Comment by cthoyt** [comment]
Indeed, for all entries in the OBO Foundry, it should be possible to generate PURLs with the following code:

```python
>>> import bioregistry
>>> bioregistry.get_obofoundry_link('clo', '1234')
'http://purl.obolibrary.org/obo/CLO_1234'

Let me know if there are non-OBO Foundry prefixes for which we could generate PURLs like this. We could either maintain a curated list in the Bioregistry (not preferred) or hopefully pull some config files from the corresponding github repo for purl.obolibrary.org
